/**
 * Pagefind search. The index + WASM are only fetched the first time
 * someone actually searches. Opens the <dialog> from any [data-search-open]
 * link, "/" or Ctrl/⌘+K; without JS those links simply go to /search/.
 */
type PagefindResult = {
  url: string;
  excerpt: string;
  meta: { title?: string; kind?: string };
};
type Pagefind = {
  options: (o: Record<string, unknown>) => Promise<void>;
  debouncedSearch: (q: string, o?: unknown, ms?: number) => Promise<{ results: { data: () => Promise<PagefindResult> }[] } | null>;
};

const BASE = import.meta.env.BASE_URL.replace(/\/?$/, '/');
// One shared promise: every caller waits for import + options() to finish,
// so no search can run before baseUrl is configured.
let loading: Promise<Pagefind | null> | null = null;

function load(): Promise<Pagefind | null> {
  loading ??= (async () => {
    try {
      // Runtime URL: produced by `pagefind --site dist` after the Astro build.
      const pf = (await import(/* @vite-ignore */ `${BASE}pagefind/pagefind.js`)) as Pagefind;
      await pf.options({ baseUrl: BASE, excerptLength: 22 });
      return pf;
    } catch {
      return null;
    }
  })();
  return loading;
}

function el<K extends keyof HTMLElementTagNameMap>(tag: K, cls: string, text?: string) {
  const n = document.createElement(tag);
  n.className = cls;
  if (text) n.textContent = text;
  return n;
}

function wire(ui: HTMLElement) {
  const input = ui.querySelector<HTMLInputElement>('[data-search-input]')!;
  const status = ui.querySelector<HTMLElement>('[data-search-status]')!;
  const list = ui.querySelector<HTMLOListElement>('[data-search-results]')!;
  ui.querySelector('form')!.addEventListener('submit', (e) => e.preventDefault());

  let seq = 0;
  const run = async () => {
    const q = input.value.trim();
    const mine = ++seq;
    if (!q) {
      list.replaceChildren();
      status.textContent = 'Type to search. Esc closes.';
      return;
    }
    status.textContent = 'Watching…';
    const pf = await load();
    if (!pf) {
      status.textContent = 'Search index not found. It is generated by `npm run build`.';
      return;
    }
    const res = await pf.debouncedSearch(q, {}, 150);
    if (!res || mine !== seq) return; // superseded by a newer keystroke
    const data = await Promise.all(res.results.slice(0, 8).map((r) => r.data()));
    if (mine !== seq) return;
    list.replaceChildren(
      ...data.map((d) => {
        const li = document.createElement('li');
        const a = el('a', 'r-link');
        a.href = d.url;
        a.append(el('span', 'r-kind', d.meta.kind ?? 'Post'), el('span', 'r-title', d.meta.title ?? d.url));
        const ex = el('span', 'r-excerpt');
        ex.innerHTML = d.excerpt; // Pagefind's excerpt: our own content + <mark> highlights
        a.append(ex);
        li.append(a);
        return li;
      }),
    );
    status.textContent = data.length
      ? `${res.results.length} result${res.results.length === 1 ? '' : 's'} for “${q}”`
      : `Nothing for “${q}”. The watcher saw nothing.`;
  };
  input.addEventListener('input', run);
  return { input, run };
}

// ---- inline UI on /search/ (supports ?q=) ----
for (const ui of document.querySelectorAll<HTMLElement>('[data-search-ui]')) {
  if (ui.closest('dialog')) continue;
  const { input, run } = wire(ui);
  const q = new URLSearchParams(location.search).get('q');
  if (q) {
    input.value = q;
    run();
  }
}

// ---- dialog ----
const dialog = document.querySelector<HTMLDialogElement>('[data-search-dialog]');
if (dialog) {
  const ui = dialog.querySelector<HTMLElement>('[data-search-ui]')!;
  const { input } = wire(ui);
  const open = () => {
    if (!dialog.open) dialog.showModal();
    input.select();
    void load(); // warm the index while the user types
  };
  document.addEventListener('click', (e) => {
    const trigger = (e.target as HTMLElement).closest('[data-search-open]');
    if (!trigger || e.defaultPrevented || e.metaKey || e.ctrlKey || e.shiftKey) return;
    e.preventDefault();
    (trigger.closest('details') as HTMLDetailsElement | null)?.removeAttribute('open');
    open();
  });
  dialog.querySelector('[data-search-close]')!.addEventListener('click', () => dialog.close());
  // Esc in a type=search input only clears it by default; close in one press.
  dialog.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') {
      e.preventDefault();
      dialog.close();
    }
  });
  // click on the backdrop closes
  dialog.addEventListener('click', (e) => {
    if (e.target === dialog) dialog.close();
  });
  document.addEventListener('keydown', (e) => {
    const t = e.target as HTMLElement;
    const typing = t.isContentEditable || /^(INPUT|TEXTAREA|SELECT)$/.test(t.tagName);
    if ((e.key === 'k' && (e.metaKey || e.ctrlKey)) || (e.key === '/' && !typing)) {
      e.preventDefault();
      open();
    }
  });
}

export {};
